apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-controller-api-deployment
  namespace: lab-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-controller-api
  template:
    metadata:
      labels:
        app: lab-controller-api
    spec:
      serviceAccountName: lab-controller-account
      containers:
        - name: lab-orchestrator-api
          image: biolachs2/lab_orchestrator:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          env:
            - name: DATABASE_ENGINE
              value: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: mail-config
