apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-config
  namespace: lab-controller
  labels:
    app: lab-config
data:
  # Django Startup
  DJANGO_SUPERUSER_EMAIL: "admin@domain.com"
  DJANGO_SUPERUSER_PASSWORD: "secret"
  DJANGO_SUPERUSER_USERNAME: "admin"
  AMOUNT_WORKERS: "5"
  # Mail
  EMAIL_USE_TLS: "True"
  EMAIL_HOST: "domain.com"
  EMAIL_PORT: "587"
  EMAIL_HOST_PASSWORD: "secret"
  EMAIL_HOST_USER: "noreply@domain.com"
  DEFAULT_FROM_EMAIL: "noreply@domain.com"
  # Django Settings
  SECRET_KEY: "secret_key_for_testing"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost;127.0.0.1"
  USE_X_FORWARDED_HOST: "True"
  DEVELOPMENT: "False"
