apiVersion: v1
kind: ServiceAccount
metadata:
  name: lab-controller-api-account
  namespace: lab-controller
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lab-controller-api-account
  namespace: lab-controller
rules:
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
      - virtualmachineinstances
      - virtualmachineinstancepresets
      - virtualmachineinstancereplicasets
      - virtualmachineinstancemigrations
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lab-controller-api-account
  namespace: lab-controller
subjects:
  - kind: ServiceAccount
    name: lab-controller-api-account
    namespace: lab-controller
roleRef:
  kind: ClusterRole
  name: lab-controller-api-account
  apiGroup: rbac.authorization.k8s.io
