# Generated by Django 3.2.6 on 2021-09-24 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_orchestrator_lib_django_adapter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='lab_orchestrator_lib_django_adapter.labmodel')),
            ],
        ),
    ]
